export default {
  AUT_CHECK: 'AUT_CHECK',
  AUT_CHECK_LOADING: 'AUT_CHECK_LOADING',
  AUT_CHECK_ERROR: 'AUT_CHECK_ERROR',

  AUT_LOGIN: 'AUT_LOGIN',
  AUT_LOGIN_LOADING: 'AUT_LOGIN_LOADING',
  AUT_LOGIN_ERROR: 'AUT_LOGIN_ERROR',

  AUT_SET_LOGGED: 'AUT_SET_LOGGED',
  AUT_SET_USER: 'AUT_SET_USER',
  AUT_SET_APW: 'AUT_SET_APW',
  AUT_SET_ROLES: 'AUT_SET_ROLES',

  AUT_LOGOUT: 'AUT_LOGOUT',
  AUT_SET_LOADING: 'AUT_SET_LOADING',
  AUT_SET_ONBOARDING: 'AUT_SET_ONBOARDING',
};
